name: UserStory_Validation
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - development
      - hotfix-*
      - Release-*
 
      
jobs:
  check_US_Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: check_US_Integration
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          gh pr view $PR_NUMBER >> comments.txt 
          comment=$(grep "AB#" comments.txt)
          echo $comment is comment
          ad_num=$(echo $comment | awk -F']' '{print $1}')
          echo $ad_num
          ad_num1="${ad_num#?}"
          echo $ad_num1
          echo $ad_num1 is AzureDevOps User Story
          if [[ $ad_num1 =~ ^AB#.*[0-9]$ ]];then
            echo Valid UserStory.. 
            exit 0
          else
            echo Invalid UserStory..Please append UserStory number after AB#...Exiting!!
            exit 1
          fi  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
