name: Child2

on:
  workflow_call:
    inputs:
      Brand:
        required: true
        type: string
    secrets:
      REPO:
        required: true

jobs: 
  Child2: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - run: |
          echo -----------------------run-id-----------------------------
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.REPO }}" "https://api.github.com/repos/2115-27/hello-world-npm/actions/workflows/parent.yml/runs?status=in_progress" 
          RUN_ID=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.REPO }}" "https://api.github.com/repos/2115-27/hello-world-npm/actions/workflows/parent.yml/runs?status=in_progress" |  jq -r '.workflow_runs[0].id')
          echo RUN_ID: $RUN_ID
          echo ----------------------run-name--------------------------
          RUN_NAME=$(curl -H "Authorization: Bearer ${{ secrets.REPO }}" "https://api.github.com/repos/2115-27/hello-world-npm/actions/runs/$RUN_ID" |  jq -r '.name')
          echo RUN_NAME: $RUN_NAME
        env:
          GH_TOKEN: ${{ SECRETS.REPO }}

      - run: sleep 120 
      
#       - run: |
#             echo test
#             echo ${{ vars.BRAND1 }} is status of BRAND1
#             echo completed > myfile.txt 
#             cat myfile.txt
#             gh variable set BRAND1 < myfile.txt
#             echo ${{ vars.BRAND1 }} is status of BRAND1 after updation
#         env:
#             GH_TOKEN: ${{ secrets.REPO }}
